### ISSUE TITLE
hey i am new in this feild and i am facing this while testing 

### ISSUE THREAD

**Issue by studentnoo** [aladinyo/WhatsappyApp#10]
![hub](https://user-images.githubusercontent.com/86470814/129490901-6db40108-139e-4c48-b4e7-efd2b159d17f.JPG)

**Comment by studentnoo** [comment]
please help me i want this project badely

**Comment by theadp** [comment]
remove that loadfirebase

**Comment by erisvaldo7777** [comment]
I removed

**Comment by theadp** [comment]
i also removed

**Comment by theadp** [comment]
> I removed
hey do you know how to solve it
when i click sign in google button it opens sign in tab and i choose the account and the tab closes after the tab closes it must goto the chat screen but it is not going it is opening the same google auth tab please solve fast

**Comment by aladinyo** [comment]
hello there sorry for not replying check this out this closed issue https://github.com/aladinyo/WhatsappyApp/issues/4
if you need help reply to this and don't forget to check all closed issues

**Comment by studentnoo** [comment]
thanks for the help
