### ISSUE TITLE
google sign in repeating

### ISSUE THREAD

**Issue by theadp** [aladinyo/WhatsappyApp#12]
when i click sign in google button it opens sign in tab and i choose the account and the tab closes after the tab closes it must goto the chat screen but it is not going it is opening the same google auth tab please solve fast
@aladinyo

**Comment by aladinyo** [comment]
hello there your issue was solved here https://github.com/aladinyo/WhatsappyApp/issues/4
also don't forget to check other closed issues.
If you need help reply to this

**Comment by theadp** [comment]
> hello there your issue was solved here #4
> also don't forget to check other closed issues.
> If you need help reply to this

no bro i cant find solution from that

**Comment by theadp** [comment]
my exact problem is
when i click sign in with google it redirect google auth and i select the account and it wil; redirects to the page i shows loading icon then immediately it redirects again to the google auth and it repeates

**Comment by theadp** [comment]
i cant see any issues on my console

**Comment by theadp** [comment]
hey its urgent please solve it @aladinyo 
please check any changes in your code other than you posted in github

**Comment by theadp** [comment]
thank you vey much @aladinyo 
the issue was on the version collection in that instead of number i select string and put my value .
