### ISSUE TITLE
Install on VPS Server

### ISSUE THREAD

**Issue by issoufaao** [aladinyo/WhatsappyApp#13]
Hello, I'm working on a project and I found your WhatsApp Clone, I want to use it in the chat section of my project, Can you explain me how to install it on a VPS Server ? I'm a PHP developer, it's my first time with npm

**Comment by aladinyo** [comment]
Hello sir,
You just have to host the frontend on firebase it's free which will be in the build folder after you build the react app.
then just host the backend folder on vps server and to run the app simply run "node index" on the root of the folder
