### ISSUE TITLE
Error in snapshot listener: FirebaseError: Missing or insufficient permissions

### ISSUE THREAD

**Issue by iovoz** [aladinyo/WhatsappyApp#17]
![image](https://user-images.githubusercontent.com/18189938/151657301-c6f2d780-a1e3-429b-b010-fdc7b115d931.png)

Hi bro, may I have your suggestion? where is config wrong? 
Thanks. @aladinyo

**Comment by aladinyo** [comment]
Hey man please check out other closed issues and come back to me, and make sure you read them well

**Comment by iovoz** [comment]
> Hey man please check out other closed issues and come back to me, and make sure you read them well

Bro, thanks for reply, I checked all the closed issue, here are my db config, still has problem.

![image](https://user-images.githubusercontent.com/18189938/151666434-4191b1c9-060c-423f-9eee-5b889acc3e2a.png)

![image](https://user-images.githubusercontent.com/18189938/151666447-a55eeb78-4978-4e6e-8198-71e1f2ca43e0.png)

![image](https://user-images.githubusercontent.com/18189938/151666530-a7deabda-9350-48ad-8b91-6c816e3cba52.png)

**Comment by aladinyo** [comment]
version field have to be a number not a string

**Comment by iovoz** [comment]
> Bro, thanks for reply, I checked all the closed issue, here are my db config, still has problem. @aladinyo

Thanks, I can login now...but when I click rooms and users, an error keep looping, is there anything I missed?

![image](https://user-images.githubusercontent.com/18189938/151667112-29dc1dcb-a594-42d2-8c54-52f7c8403df3.png)

**Comment by iovoz** [comment]
> version field have to be a number not a string

Thanks, I can login now...but when I click rooms and users, an error keep looping, is there anything I missed?

![image](https://user-images.githubusercontent.com/18189938/151667193-165d1514-c19f-416f-aca1-e4c5c0ef6d55.png)

**Comment by iovoz** [comment]
> version field have to be a number not a string

Thanks man!!

**Comment by aladinyo** [comment]
no problem

**Comment by aladinyo** [comment]
make sure you put a star I would really appreciate it

**Comment by iovoz** [comment]
> make sure you put a star I would really appreciate it

Sure, I would love to..
