### ISSUE TITLE
GDPR Compliance (BIG SECURITY ISSUE)

### ISSUE THREAD

**Issue by w-henderson** [aladinyo/WhatsappyApp#3]
## Breach of Article 17 (Right to Erasure)
Excerpt from [GDPR Article 17](https://gdpr-info.eu/art-17-gdpr/):

> The data subject shall have the right to obtain from the controller the erasure of personal data concerning him or her without undue delay and the controller shall have the obligation to erase personal data without undue delay...

As this project copies data from the linked Google accounts into its database, it is the responsibility of the project owner and not Google to protect it. It is a requirement that there either be functionality within the application to remove all personal data, including user data, messages, rooms, voice messages, and images, or that the project owner responds to requests for erasure respectfully and honors them, not like this:

> I didn't implement that feature but don't worry nothing will happen...
\- <cite>[aladinyo, on Dev.to](https://dev.to/aladinyo/comment/1df51)</cite>

> this is an opane source project it's not an official app !!!
\- <cite>[aladinyo, on Dev.to](https://dev.to/aladinyo/comment/1df9o)</cite>

## Breach of Article 32 (Security of Processing)
Excerpt from [GDPR Article 32](https://gdpr-info.eu/art-32-gdpr/):

> ...the controller and the processor shall implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk...

This involves suitable encryption and anonymization of personal data, which this project does not do. Furthermore, you falsely claimed to be using encryption in your database, which after analyzing the source code and the compiled application, no encryption is used. 

> ...nothing will happen the data is encrypted...
\- <cite>[aladinyo, on Dev.to](https://dev.to/aladinyo/comment/1df51)</cite>

You then further clarified that, by encryption, you were referring to [Cloud Firestore Security Rules](https://firebase.google.com/docs/firestore/security/get-started), which is misleading, but if the rules were actually implemented, the data would be secure enough to meet the standards of Article 32.

> with firebase you can set security rules for specific documents and collections in the backend.
\- <cite>[aladinyo, on Dev.to](https://dev.to/aladinyo/comment/1df5d)</cite>

You haven't implemented any security rules on your database as far as I can see, and after some deeper investigation, I have found myself able to theoretically access the entire unencrypted database. Of course, I don't intend to steal anyone's personal data, and instead I am looking to help you secure it. While you have hidden the Firebase credentials from the GitHub repository, they are embedded in the client builds (as they need to be), so you should never consider the credentials as your only line of defense.

I recommend learning about Cloud Firestore Security Rules and implementing them as soon as possible. Ideally, you would've done this before manipulating a large number of people on Dev.to into giving your insecure application access to their personal data through their Google accounts, but there's no time like the present!

If I were you, I would completely disable all reads and writes on the database while you fix this issue, as leaving the database open would still allow attackers to access people's personal data while you work on a fix.

**Comment by jornetsimon** [comment]
This is absolutely right. Even with no encryption, security rules should be set correctly. From what I found, I agree to say this is not the case.

What is even more troubling is the fact that the maintainer is **actively hiding comments** regarding security on Dev.to.
[Example 1](https://dev.to/williamhenderson/comment/1dff7)
[Example 2](https://dev.to/pstark/comment/1dgmh)
[Example 3](https://dev.to/williamhenderson/comment/1df5f)

As unrelated these facts may be regarding the repo, it questions the the maintainer's intentions on these concerns.
