### ISSUE TITLE
A error whit doc.data()

### ISSUE THREAD

**Issue by caiobraga** [aladinyo/WhatsappyApp#4]
I just cloned the project and received this error: 
![WhatsApp-Clone-PWA](https://user-images.githubusercontent.com/45905947/116123384-54eda680-a699-11eb-8b47-cc51c7df083b.png)

I would like your help. Could you explain what "doc.data()" is. And what could be the error. I would be really thankful

**Comment by aladinyo** [comment]
of course whenever you don't understand something post an issue about it.
@caiobraga please tell me in which file and line this error is happening also did you set up a firebase project and copied and pasted the firebase config object in "firebase.js" file ???

**Comment by caiobraga** [comment]
thak you for the time anjd atention, i did the configuration of firebase.js. the error appeared in the line 111 of the src/App.js

**Comment by caiobraga** [comment]
I also changed the databaseURL in the backend/index.js file to the one that I have in firebase.

**Comment by aladinyo** [comment]
Ok I know what's the problem.
you see this app caches the frontend assets and in firestore there should be a collection "version" and there is a document in it "version" which has one property "version" which holds a number now you can give it any number and if you do some changes in your app and deploy them just increment that number and your frontend will automatically get the new assets.
So in order to fix your error create that collection.

**Comment by aladinyo** [comment]
Do it like this:
![Screenshot (1)](https://user-images.githubusercontent.com/49879567/116411609-89e72e00-a83e-11eb-9d63-90d1afafe257.png)

**Comment by caiobraga** [comment]
I will try it. come back if the answer in a second

**Comment by caiobraga** [comment]
![Captura de tela de 2021-04-28 10-44-38](https://user-images.githubusercontent.com/45905947/116414405-d0249900-a80e-11eb-80bd-6e83aa743099.png)

iI see an upgrade!!!

that is the response now

**Comment by caiobraga** [comment]
what are the permissions in the firebase? i let them as a test

**Comment by caiobraga** [comment]
can that be the error?

**Comment by aladinyo** [comment]
Show at what file and line that error happened.
But I think it's from your firebase config or security rules because if you allow reads for authenticated users only the app won't be able to read the version collection so change the security rules

**Comment by aladinyo** [comment]
this is my rules:
`rules_version = '2';  
service cloud.firestore {  
  match /databases/{database}/documents {  
    match /{document=**} {  
      allow write, read: if (request.auth.uid != null);  
    }  
		match /version/version {  
       allow read;  
       allow write: if false;  
    }  
  }  
}`

as you can see I allow read for the version collection

**Comment by caiobraga** [comment]
it was different than mine, but it was not it.

**Comment by caiobraga** [comment]
CONFIGURATION_NOT_FOUND is the error, so I guess is some mistake that I made in the configuration process. 
the databaseURL that I changed was from the real-time database. is this a problem?

**Comment by caiobraga** [comment]
I get it now, it must be it then. thank you very much.

**Comment by caiobraga** [comment]
just an update. I found the second error, it was because I did not set the sign-in method in firebase. Sorry for the bad English btw. I am Brazilian so..

**Comment by aladinyo** [comment]
No problem man you're welcome
