### ISSUE TITLE
How to add new line in message?

### ISSUE THREAD

**Issue by lovleshsingh** [aladinyo/WhatsappyApp#8]

**Comment by Bellisario** [comment]
This is not possible, for now...
The problem is that needs to work using shift+enter (as real WhatsApp), but seems it sends message as enter.

**Comment by lovleshsingh** [comment]
Yes, Shift+enter is does work if input tag is changed to textarea tag, but when message is send it goes in one line. This is because firestore database stores the strings in one line.

**Comment by Bellisario** [comment]
Mmm, I think some changes needs to be made...

**Comment by lovleshsingh** [comment]
> Mmm, I think some changes needs to be made...

If you find a solution for this kindly let me know

**Comment by theadp** [comment]
can anyone help me

**Comment by aladinyo** [comment]
hello there you need to change the input to <textarea> tag but you will have a lot to style but it's a good exercise, I hope I helped you.
